bind_addr: ":8001"

jwt_secret_key: "sdvm-vppparv324-gdgmfopmgphmspsfvs3vddf5vdbdnfhmd4"
jwt_access_token_life_time: 60
jwt_refresh_token_life_time: 3600

mongodb_connection_string: "mongodb://localhost:27017"

roles:
  -
    name: authenticated
    desc: Authenticated user
  -
    name: task_creator
    desc: Task creator
  -
    name: analyst
    desc: Analyst

users:
  -
    username: user1
    password: $2a$10$OgcMhbZH5BX5cXssxeGz5uNbjLSStpp76lnUMQqLbV8bZwGzOm/va
    roles:
      - task_creator
      - authenticated
  -
    username: user2
    password: $2a$10$fWVsdKGXuOxMzL0tahrd2./BjJHasZ7QvdGJWjtpbV0aUbswVmdhC
    roles:
      - analyst
      - authenticated
  -
    username: user3
    password: $2a$10$pmoTf7xqk9Ik0FF4FiDq6uZzYpzCXHy98.mJokbejSmiypLYFLs3C
    roles:
      - authenticated
  -
    username: test123
    password: $2a$10$fvuY45K46bV5iWinqi1yg.N/uQUsTYo8Y6MgaF2KYZ5QFhNCZiT8a
    roles:
      - task_creator
      - authenticated

